version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db:3306/finance_hub
      - JWT_SECRET=your_secure_jwt_secret_key
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - finance-network
    command: npm run start:dev

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: finance_hub
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - finance-network

networks:
  finance-network:
    driver: bridge

volumes:
  mysql-data:
